version: '3'

services:
    bot:
        build: .
        env_file:
            - .env
        volumes:
            - .:/app
        links:
            - 'mongodb:mongodb'
        restart: always
    mongodb:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data_container:/data/db
volumes:
    mongodb_data_container:
